#pragma once

#include "Settings.hpp"

enum
{
	ID_Help = 1,
	ID_About,
	ID_Quit,
	ID_10msTimer,
	ID_100msTimer,
	ID_CheckKeypress,
	ID_FilePicker,
	ID_FilePickerMapConverter,
	ID_FilePickerCanScript,
	ID_DestroyAll,
	ID_CanLoadTxList,
	ID_CanSaveTxList,
	ID_CanLoadRxList,
	ID_CanSaveRxList,
	ID_CanLoadMapping,
	ID_CanSaveMapping,
	ID_CanSaveAll,
	ID_CmdExecutorSave,
	ID_BsecSaveCache,
	ID_SaveEverything,
	ID_EditSettings,
	ID_ReloadSettings,
	ID_AppBindListMain,
	ID_MacroDetails,
	ID_BackupPanel,
	ID_EditorPropGrid,
	ID_DirList,
	Id_Macro_AddNewApplication,
	Id_Macro_AddNewMacroKey,
	Id_Macro_Rename,
	Id_Macro_Delete,
	Id_MacroDetails_AddNew,
	Id_MacroDetails_Clone,
	Id_MacroDetails_Delete,
	Id_MacroDetails_MoveUp,
	Id_MacroDetails_MoveDown,
	ID_CanLogLevelSpinCtrl,
	ID_ModbusCustomCommand,
};
