#pragma once

// The application precompiled header: the headless core plus wxWidgets, the GUI
// panels and the application services. Only GUI-target translation units may
// use it; headless code includes "pch_core.hpp" and its own dependencies.

#include "pch_core.hpp"

#include <wx/aui/aui.h>
#include <wx/statline.h>
#include <wx/clipbrd.h>
#include <wx/valnum.h>
#include <wx/spinctrl.h>
#include <wx/richtooltip.h>
#include <wx/richmsgdlg.h>
#include <wx/filepicker.h>
#include <wx/tglbtn.h>
#include <wx/dataview.h>
#include <wx/propgrid/propgrid.h>
#include <wx/propgrid/advprops.h>
#include "wx/treelist.h"
#include "wx/treectrl.h"
#include <wx/dirctrl.h>
#include <wx/xml/xml.h>
#include "wx/notifmsg.h"
#include "wx/generic/notifmsg.h"
#include <wx/menu.h>
#include "wx/taskbar.h"
#include <wx/wxprec.h>
#include <wx/gbsizer.h>
#include <wx/grid.h>
#include <wx/datectrl.h>
#include <wx/dateevt.h>
#include <wx/timectrl.h>
#include <wx/calctrl.h>
#include <wx/srchctrl.h>
#include <wx/fontpicker.h>
#include <wx/artprov.h>
#include <wx/tipwin.h>

#include "gui/BitFieldEditorDialog.hpp"
#include "gui/CanPanel/CanLogPanel.hpp"
#include "gui/CanPanel/CanPanel.hpp"
#include "gui/CanPanel/CanScriptPanel.hpp"
#include "gui/CanPanel/CanSenderPanel.hpp"
#include "gui/CanPanel/CanUdsRawDialog.hpp"

#include "gui/ConfigurationBackup.hpp"
#include "gui/DebugPanel.hpp"
#include "gui/gui_id.hpp"
#include "gui/EscaperPanel.hpp"
#include "gui/LogPanel.hpp"
#include "gui/FilePanel.hpp"
#include "gui/TrayIcon.hpp"
#include "gui/MainPanel.hpp"
#include "gui/MainFrame.hpp"
#include "gui/SettingsDialog.hpp"
#include "gui/ModbusDialogs.hpp"
#include "gui/ModbusGraphView.hpp"
#include "gui/ModbusMasterPanel.hpp"
#include "gui/CmdExecutorPanel.hpp"
#include "gui/DidPanel.hpp"
#include "gui/AlarmPanel.hpp"
#include "gui/TimeTrackerPanel.hpp"

#include "Logger.hpp"
#include "WindowsAddon.hpp"
#include "CustomMacro.hpp"
#include "DatabaseImpl.hpp"
#include "MeasurementRepository.hpp"
#include "GraphGenerator.hpp"
#include "DatabaseLogic.hpp"
#include "SensorDataParser.hpp"
#include "Settings.hpp"
#include "Server.hpp"
#include "Sensors.hpp"
#include "DirectoryBackup.hpp"
#include "PrintScreenSaver.hpp"
#include "PathSeparator.hpp"
#include "Session.hpp"
#include "SerialTcpBackend.hpp"
#include "IdlePowerSaver.hpp"
#include "TerminalHotkey.hpp"
#include "SerialPortBase.hpp"
#include "SerialPort.hpp"
#include "CanSerialPort.hpp"
#include "CanDeviceStm32.hpp"
#include "CanDeviceLawicel.hpp"
#include "ModbusMasterSerialPort.hpp"
#include "ModbusHandler.hpp"
#include "CryptoPrice.hpp"
#include "CanModels.hpp"
#include "CanXmlLoaders.hpp"
#include "CanEntryHandler.hpp"
#include "DidHandler.hpp"
#include "CanScriptHandler.hpp"
#include "CorsairHid.hpp"
#include "StringToCEscaper.hpp"
#include "TcpMessageExecutor.hpp"
#include "CmdExecutor.hpp"
#include "ExceptionHandler.hpp"
#include "BsecHandler.hpp"
#include "ImageRecognition.hpp"
#include "Alarms.hpp"
#include "WorkingDays.hpp"
#include "TimeTracker.hpp"
#include "ScriptLauncher.hpp"
#include "Utils.hpp"
